name: 🐛 Bug Report
description: Report an unexpexted behaviour
title: "[BUG]: "
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        Issues are formatted using markdown, a useful summary of the features provided by GitHub can be found [here](https://guides.github.com/pdfs/markdown-cheatsheet-online.pdf).
  - type: textarea
    attributes:
      label: Steps to Reproduce
      description: Please provide detailed steps for reproducing the issue.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected Behavior
      description: A concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Current behavior
      description: A concise description of what you're experiencing.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Context
      description: Please provide any relevant information about your setup. This is important in case the issue is not reproducible except when under certain conditions.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Logs
      description: Please include any relevant log here. Complete log files are preferred, remember to anonymise any personal data in it (text format is preferrable than screenshot).
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Checks
      description: By submitting this issue, you agree to follow our Code of Conduct.
      options:
        - label: I am running the latest version
          required: true
        - label: I checked the documentation and found no answer
          required: true
        - label: I checked to make sure that this issue has not already been filed
          required: true
        - label: I'm reporting the issue to the correct repository
          required: true
